# Generated by Django 2.0 on 2018-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrongKrongCrawl', '0002_auto_20180105_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpengData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
